spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/spacely
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
